language: node_js
node_js:
- 7.8
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'lightlayer.martinmetodiev.com' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    secure: IWGOYiStyfVuWL0e4dkLmJDg/rT75Mp7YMf76GO4Ppxs6JeJ39KLqEPwnyYgcf04lqJ6qu+7ti9ajcsiw7JUTmjVZWZsmeNZPg2zDkASEQw91pi7o9+4wQdYtHiUqn4tqQewIgYZ6goQlJ0dHsbwKGRDuwxMCTqOibqpWOB2X6tTsiwiSbQT5oREym83qei1qGIK9XhQTpSJW4F4qhZ8QlXoOzJwN3RD8HVwsXecdh6gVHDmeZFOhhwPKXVRoLGR1rrESy2llFMMGJBWWwEPgmtPGYZzSQC0xwK7u0KaVebTGS1zoi9SEQkhHPOPFcmtgpKeCIIzhpH8WZjjHYBZZ1OWbRPzQbLkvQCDvec7h33gRU1CPokSmEdK0Bp6hVAHj5K46mkpHFKPhxhC4eDnVBmgb3sVFK+MDMokCz70B48WKXSw6uPyfxZ/qpUX+E9UfjhZ65hF53tf6YM5eUiV33Vo45WWUEBTIB/2PUnBWr2xjUIB+N71jVb5JnHp9Swf8Zg1qY1frhjYb7kYCBGEnJNkABblVYOQPWRVxA7wA5Yx9OpO2ae9NSpIIyoAbAUzC5n1bwxZn0JgwzJGaOUgAhKx8r/tBWhHoLGYFNSaxwcu2aU2UfpXcLkZmzFA0tx6Tf2dcdPuCSxv92DyxMKDEKGxe7A3VYRwpcmslRSEL7c=
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: WTzgGmZGT/49t2yJzXe5dNTo+GrWoz/SDe2+V/dZnc4ENqxoMQnKuHYyiae/h4c8oX989HDN9shUIEue6IfzAQqjizW540pOeqAxLw/EW/oI7+xvjx/0xTWTxyE0eZqW+9ZXypWDKE1Tdw8VR3leD7SQ7VAi/tC20eeQuTVl3AnDlOuh6gyZGd8mZClxKDVIzfBdUZ2cqfCtkk2b/ujQswlE9tuj9AvoKnQoDfWVI3g6RdkUA2CDimpWDDxYriijPmdOIXyvFJx4RydwxwC4u6vmq7uqE6eXgwBEpM4p3Iwu0YE0r+g/n1pe3izuenOXygBrLBhwUxuwccRt6DcN7fI9knRxHgvheGwxjePzzb6TjDRbx+lVsKEhQNJBQkXdHJSeuO2dmq5z1KV0I7a9SzPpr2N5lAXymbKzRqO7z6ac3uCSqq7lcO3xPY0CpIbOk1iW24QJqcIhKgNWB7WNviexil78hqqnwNtn6Lx3/b7pCX9rDMORvHuyaSSwo8X3C/BoMoZVDfs3kUu711u8XcGtKMhw+P0smxZv833M6M6+uV2ULrZatb3SxjSOjfDQvFraeTNvdfXI3EuqQSdNP3M3v9mQ/5xtzmQQS71bwG8nfK6uLjrJZGlNYWmYiSySP4ntLCr/TUpzQ+Rz89fCbgyiKiP8F/iAyio8W0yAvPg=
  on:
    tags: true
- provider: releases
  api_key:
    secure: WTzgGmZGT/49t2yJzXe5dNTo+GrWoz/SDe2+V/dZnc4ENqxoMQnKuHYyiae/h4c8oX989HDN9shUIEue6IfzAQqjizW540pOeqAxLw/EW/oI7+xvjx/0xTWTxyE0eZqW+9ZXypWDKE1Tdw8VR3leD7SQ7VAi/tC20eeQuTVl3AnDlOuh6gyZGd8mZClxKDVIzfBdUZ2cqfCtkk2b/ujQswlE9tuj9AvoKnQoDfWVI3g6RdkUA2CDimpWDDxYriijPmdOIXyvFJx4RydwxwC4u6vmq7uqE6eXgwBEpM4p3Iwu0YE0r+g/n1pe3izuenOXygBrLBhwUxuwccRt6DcN7fI9knRxHgvheGwxjePzzb6TjDRbx+lVsKEhQNJBQkXdHJSeuO2dmq5z1KV0I7a9SzPpr2N5lAXymbKzRqO7z6ac3uCSqq7lcO3xPY0CpIbOk1iW24QJqcIhKgNWB7WNviexil78hqqnwNtn6Lx3/b7pCX9rDMORvHuyaSSwo8X3C/BoMoZVDfs3kUu711u8XcGtKMhw+P0smxZv833M6M6+uV2ULrZatb3SxjSOjfDQvFraeTNvdfXI3EuqQSdNP3M3v9mQ/5xtzmQQS71bwG8nfK6uLjrJZGlNYWmYiSySP4ntLCr/TUpzQ+Rz89fCbgyiKiP8F/iAyio8W0yAvPg=
  skip_cleanup: true
  on:
    tags: true
